blank_issues_enabled: false
contact_links:
  - name: Contact form
    url: https://www.zhaw.ch/en/about-us/person/rata/
    about: If you have question that you want to ask privately, contact Nils here
