name: Contact-form
description: Fill out this contact from to show your interested in participating in the DataChallange and successive Hackdays (non-binding)
title: I'm intersted in participating 
labels: ["bug", "triage"]
assignees:
  - ratnanil
body:
  - type: markdown
    attributes:
      value: |
        Thank you for showing interest in our DataChallange and the Hackdays. Fill out this form so we know more about you!
  - type: input
    id: name
    attributes:
      label: Name
      description: Tell us your name (you can use a pseudonym if you want to)
      placeholder: Your Name
    validations:
      required: true
  - type: input
    id: kuerzel
    attributes:
      label: ZHAW Username
      description: Provide your ZHAW Username ("Kürzel")
      placeholder: e.g. rata
    validations:
      required: true
  - type: dropdown
    id: sureness 
    attributes:
      label: Sure
      description: How certain are you that you want to participate?
      options:
        - Very certain (Default)
        - Not sure
        - Definitly not
    validations:
      required: true
  - type: textarea
    id: textarea
    attributes:
      label: Free Text
      description: Anything else you want to tell us?
  - type: dropdown
    id: programme 
    attributes:
      label: Your status at ZHAW (optional)
      options:
        - Bachelor
        - Master
        - Empoloyee
        - other
  - type: dropdown
    id: institute
    attributes:
      label: Your institute (optional)
      options:
        - ICBT Institut für Chemie und Biotechnologie
        - IFM Institut für Facility Management
        - ILGI Institut für Lebensmittel- und Getränkeinnovation
        - IUNR Institut für Umwelt und Natürliche Ressourcen
        - ICLS Institut für Computational Life Sciences
        - other
